on: [push]

jobs:
    build:
        name: Push Sphinx Pages
        runs-on: ubuntu-latest
        steps:
            - uses: l-gorman/legume-choice-docs@main
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  create_readme: true
